FROM pytorch/pytorch:1.7.0-cuda11.0-cudnn8-runtime
pip install pylibjpeg-openjpeg yacs matplotlib scikit-image seaborn scikit-learn tensorboardX opencv-python gdown
RUN apt-get update
RUN apt-get install -y libglib2.0-0 libsm6 libxext6 libxrender1 libgl1-mesa-glx zip
RUN pip install shyaml

WORKDIR /topoBoundary
